# Homework 5

## Question 1


## Question 2


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import time
from scipy.linalg import hilbert
from numpy import linalg as LA
import decimal

A = np.matrix('1 2; 0 2')
b = np.matrix('6 -4')

In [47]:
A = np.matrix('1 1 1; 0 2 5; 2 5 -1')
b = np.matrix('6; -4; 27') 
tot_it = 15

def my_jacobi(A,b,tot_it):
  C_u = np.triu(A)
  C_l = np.tril(A)
  D = A + C_u + C_l
  Dinv = np.linalg.inv(D)
  x = np.zeros((np.size(b,0),1))
  for i in range(tot_it):
    x = Dinv * (C_u + C_l)* x +Dinv*b
  return x

my_jacobi(A,b,tot_it)

matrix([[ 4.98088921],
        [ 3.00747641],
        [-2.00146829]])

In [0]:
def generate_SPD_mat_and_rhs_vector(n):
    h = 1 / (n+1)
    scal_fac = (1/(h*h))
    A = np.diag(-2*np.ones(n), 0) + np.diag(np.ones(n-1),1) + np.diag(np.ones(n-1),-1)
    A = -scal_fac*A
    x = np.arange(h,(1-h)+h,h)
    b = np.sin(2*np.pi*x)
    b[0] = b[0] - scal_fac
    b[(n-1)] = b[(n-1)] - scal_fac
    return A,b

In [89]:
N = [10,100,500,1000];
tot_it = 100
for n in N:
    (A,b) =  generate_SPD_mat_and_rhs_vector(n)
    x_jacobi = my_jacobi(A,b,tot_it)
    x_t = np.linalg.solve(A,b)
    err_jacobi = np.linalg.norm(x_t - x_jacobi)
    print(err_jacobi)

9.882588650026447
100.00436696257613
500.0779910112346
1000.1593705613177


The error increases as the system size increases.

## Question 3

In [0]:
def my_gauss_siedel(A,b,tot_it):
  C_u = np.triu(A)
  C_l = np.tril(A)
  D = A + C_u + C_l
  Dinv = np.linalg.inv(D)
  x = np.zeros((np.size(b,0),1))
  for i in range(tot_it):
    x = np.linalg.inv(D-C_l)*C_u*x+np.linalg.inv(D-C_l)*b
  return x

matrix([[ 4.99972695],
        [ 3.00010922],
        [-2.00001927]])

In [79]:
tot_its = [10,100,1000,10000]
num_experiments = 4

n = 500
[A,b] =  generate_SPD_mat_and_rhs_vector(n)

err_jacobi = np.zeros((num_experiments,1))
err_gs = np.zeros((num_experiments,1))
exp_num = 0

for tot_it in tot_its:

    x_jacobi = my_jacobi(A,b,tot_it)
    
    x_gs = my_gauss_siedel(A,b,tot_it)
  
    x_t = np.linalg.solve(A,b)
    
    err_jacobi[exp_num] = np.linalg.norm(x_t - x_jacobi)
    err_gs[exp_num] = np.linalg.norm(x_t - x_gs)
    
    exp_num = exp_num + 1
    
print(err_jacobi)

[[500.07803887]
 [500.07799101]
 [500.07799101]
 [500.07799101]]


In [87]:
print("Iterations Jacobi Err  GS Err")
for i in range(4):
  print("{}    {}    {}".format(tot_its[i],err_jacobi[i],err_gs[i]))

Iterations Jacobi Err  GS Err
10    [500.07803887]    [500.07755882]
100    [500.07799101]    [500.07755485]
1000    [500.07799101]    [500.07755485]
10000    [500.07799101]    [500.07755485]


It appears that the GS algorithm has a slightly smaller error than the Jacobi.

## Question 4
?