# Homework 9
## Jacob Traunero

## Problem 1
### Part A
#### See attached handwritten solution.

In [0]:
import numpy as np
import scipy
import math
import matplotlib.pyplot as plot
from scipy.interpolate import lagrange
from numpy.polynomial.polynomial import Polynomial
from tabulate import tabulate

### Part B

In [118]:
A = np.array([[1, -3, 3],[2, -2, 2], [2, 0, 0]])
print(np.linalg.eig(A))

(array([ 1.00000000e+00,  1.66533454e-15, -2.00000000e+00]), array([[-3.33333333e-01,  6.66133815e-16, -7.07106781e-01],
       [-6.66666667e-01,  7.07106781e-01, -4.99600361e-16],
       [-6.66666667e-01,  7.07106781e-01,  7.07106781e-01]]))


For part A, I found the eigenspaces that contain each eigenvector. The results from part B do match up, however there is a roundoff errror. 

For example, I calculated 0 for one of the eigenvalues, but got 1.66533454e-15 in part B.

### Part C
#### See attached handwritten solution.

## Problem 2
### Part A


In [0]:
def power_method(A,x,tol,verbose=False):
  val_array = []
  
  y = np.dot(A,x)
  val = max(y.min(), y.max(),key=abs)
  vect = y/val
  val_array.append(val)
  
  y = np.dot(A,vect)
  val = max(y.min(), y.max(),key=abs)
  vect = y/val
  val_array.append(val)
  i = 1
 
  while(abs(val_array[i] - val_array[i-1])>tol):
    if(i>1000):
      print("Is not converging")
      return(val,vect)
    y = np.dot(A,vect)
    val =max(y.min(), y.max(),key=abs)
    vect = y/val
    if(verbose):
      print("Value:",val)
      print("Vector:",vect)
      print("A*b:",y)
    val_array.append(val)
    i+=1
  return val,vect

### Part B

In [224]:
val,vect = power_method(A, np.matrix('1;1;1'),10**-3)
print("i. Approximate Eigenvalue:",val)
print("   Approximate Eigenvector:\n",vect)
val2,vect2 = power_method(A, np.matrix('1;-1;1'),10**-3)
print("ii. Approximate Eigenvalue:",val2)
print("    Approximate Eigenvector:\n",vect2)

i. Approximate Eigenvalue: 1.0
   Approximate Eigenvector:
 [[0.5]
 [1. ]
 [1. ]]
ii. Approximate Eigenvalue: 1.9997253920790872
    Approximate Eigenvector:
 [[ 1.00000000e+00]
 [ 9.15485436e-05]
 [-9.99862677e-01]]


### Part D

In [229]:
B=np.array([[-3,-2],[4,3]])
val,vect = power_method(B, np.array([1,1]), 10**-3)
print("Approximate Eigenvalue:", val)
print("Approximate Eigenvector:\n", vect,"\n")
print(np.linalg.eig(B))

Is not converging
Approximate Eigenvalue: 0.1428571428571428
Approximate Eigenvector:
 [1. 1.] 

(array([-1.,  1.]), array([[-0.70710678,  0.4472136 ],
       [ 0.70710678, -0.89442719]]))


array([[-3., -2.],
       [ 4.,  3.]])

The method is not converging to an eigenvector.